"""The other thing that arrives on the Kindle each morning: how the system changed.

The digest is the product; this is the changelog for the machine that makes it.
It exists so the review loop has two halves — you read what the pipeline
produced, and you read what moved underneath it, and your feedback lands on
both.

Deliberately not generated by a model. The observations here are about work
that was done, and a model asked to describe changes it did not make will write
something plausible instead. Sections are supplied by whoever did the work; this
module only typesets them and reuses the digest's Kindle-safe CSS.
"""

import logging
import os
import subprocess
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional

from .render import _CSS, _esc, _xhtml

logger = logging.getLogger(__name__)


@dataclass
class ReportSection:
    heading: str
    # Paragraphs of prose. Rendered in order, before any bullets.
    paragraphs: List[str] = field(default_factory=list)
    bullets: List[str] = field(default_factory=list)


@dataclass
class SystemReport:
    title: str
    summary: str
    generated_at: datetime
    sections: List[ReportSection] = field(default_factory=list)

    @property
    def slug(self) -> str:
        return f"hnfm-report-{self.generated_at:%Y-%m-%d}"


def recent_commits(limit: int = 12, repo_dir: Optional[str] = None) -> List[str]:
    """Subject lines of recent commits, for the "what changed" section.

    Best-effort: the worker container has the source mounted but not always the
    .git directory, and a missing changelog is not worth failing a report over.
    """
    try:
        out = subprocess.run(
            ["git", "log", f"-{limit}", "--pretty=format:%h %s"],
            cwd=repo_dir or os.getenv("REPO_DIR", "/app"),
            capture_output=True, text=True, timeout=15,
        )
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.strip().splitlines()
    except Exception as e:
        logger.debug(f"report: git log unavailable ({e})")
    return []


def _body(report: SystemReport) -> str:
    out = [
        f"<h1>{_esc(report.title)}</h1>",
        f'<p class="meta">{report.generated_at:%A %d %B %Y}</p>',
        f'<p class="thesis">{_esc(report.summary)}</p>',
    ]
    for sec in report.sections:
        out.append('<hr class="rule"/>')
        out.append(f"<h2>{_esc(sec.heading)}</h2>")
        for para in sec.paragraphs:
            out.append(f"<p>{_esc(para)}</p>")
        if sec.bullets:
            out.append("<ul>")
            for b in sec.bullets:
                out.append(f"<li>{_esc(b)}</li>")
            out.append("</ul>")
    return "\n".join(out)


def render_html(report: SystemReport) -> str:
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>{_esc(report.title)}</title>"
        f"<style>{_CSS}\nbody{{max-width:38em;margin:0 auto;padding:2em 1.2em;}}</style>"
        f"</head><body>{_body(report)}</body></html>"
    )


def write_epub(report: SystemReport, out_path: str) -> str:
    """Reuses the digest EPUB writer by adapting the report to its shape."""
    from .render import write_epub as _write
    from .select import Digest, DigestStory
    from .compose import Section

    shell = Digest(
        title=report.title,
        subtitle=f"{report.generated_at:%A %d %B %Y}",
        generated_at=report.generated_at,
        # One placeholder story: write_epub refuses to emit an empty book, and
        # the report's content rides in `sections` rather than in stories.
        stories=[DigestStory(
            item_id=0, run=0, title=report.title, url=None,
            hn_score=0, interest=None, rank=0.0, brief={},
        )],
    )
    sections = [Section(kind="teaser", title="", body=report.summary)]
    for sec in report.sections:
        body = "\n\n".join(sec.paragraphs)
        if sec.bullets:
            body += "\n\n" + "\n\n".join(f"— {b}" for b in sec.bullets)
        sections.append(Section(kind="quick", title=sec.heading, body=body))
    return _write(shell, out_path, sections=sections)


def build_and_send(report: SystemReport, send: bool = True) -> dict:
    """Write the report and optionally email it. Returns paths and message id."""
    from .deliver import send_digest, delivery_config, DeliveryError

    out_dir = os.path.join(os.getenv("OUTPUTS_ROOT", "/app/outputs"), "reports")
    os.makedirs(out_dir, exist_ok=True)
    html_path = os.path.join(out_dir, f"{report.slug}.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(render_html(report))

    result = {"html_path": html_path, "status": "built"}
    if not send:
        return result

    ready, why = delivery_config()
    if not ready:
        result["send_error"] = why
        return result
    try:
        result["message_id"] = send_digest(
            html_path, subject=f"hn.fm System Report {report.generated_at:%d %b %Y}"
        )
        result["status"] = "sent"
    except DeliveryError as e:
        result["status"] = "built_not_sent"
        result["send_error"] = str(e)
    return result
